ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_code VARCHAR(6) DEFAULT NULL AFTER token;
ALTER TABLE users ADD COLUMN IF NOT EXISTS otp_expires DATETIME DEFAULT NULL AFTER otp_code;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at DATETIME DEFAULT NULL AFTER otp_expires;
